# Generated by Django 2.1.4 on 2019-01-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='activity_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='height',
            field=models.IntegerField(null=True),
        ),
    ]
