# Generated by Django 2.1.4 on 2019-01-18 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionapp', '0002_auto_20190109_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbmi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfood', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='macronutrient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermacronutrient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='water',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userwater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userweight', to=settings.AUTH_USER_MODEL),
        ),
    ]
