# Generated by Django 2.1.4 on 2019-01-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionapp', '0003_auto_20190118_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='macronutrient',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='body_fat',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
